- name: Install elm-format
  unarchive:
    src: https://github.com/avh4/elm-format/releases/download/0.8.0/elm-format-0.19-0.8.0-linux-x64.tgz
    dest: ~/bin
    remote_src: yes
  args:
    creates: ~/bin/elm-format
