- name: Install asdf version manager
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.7.0

- name: asdf Elixir
  command: ~/.asdf/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  args:
    creates: ~/.asdf/plugins/elixir

- name: Install Erlang compilation packages
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - erlang-wx
    - libwxgtk3.0-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libpng-dev

- name: asdf Erlang
  command: ~/.asdf/bin/asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  args:
    creates: ~/.asdf/plugins/erlang

- name: asdf NodeJS (and import NodeJS GPG keys)
  shell: |
    ~/.asdf/bin/asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  args:
    creates: ~/.asdf/plugins/nodejs

- name: asdf Ruby
  command: ~/.asdf/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
  args:
    creates: ~/.asdf/plugins/ruby

- name: asdf Terraform
  command: ~/.asdf/bin/asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git
  args:
    creates: ~/.asdf/plugins/terraform

- name: asdf OCaml
  command: ~/.asdf/bin/asdf plugin-add ocaml https://github.com/vic/asdf-ocaml.git
  args:
    creates: ~/.asdf/plugins/ocaml

- name: asdf Golang
  command: ~/.asdf/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  args:
    creates: ~/.asdf/plugins/golang

- name: asdf Python
  command: ~/.asdf/bin/asdf plugin-add python https://github.com/danhper/asdf-python
  args:
    creates: ~/.asdf/plugins/python

- name: asdf Kubectl
  command: ~/.asdf/bin/asdf plugin-add kubectl https://github.com/banno/asdf-kubectl
  args:
    creates: ~/.asdf/plugins/kubectl
