- set_fact:
    neovim_version: 0.4.2

- name: Create Neovim dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - ~/.config/nvim/autoload
    - ~/bin/nvim-{{ neovim_version }}

- name: Download Neovim AppImage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim.appimage
    dest: ~/bin/nvim-{{ neovim_version }}/nvim.appimage
    mode: 0700

- name: Extract Neovim app
  command: ./nvim.appimage --appimage-extract
  args:
    creates: ~/bin/nvim-{{ neovim_version }}/squashfs-root
    chdir: ~/bin/nvim-{{ neovim_version }}

- name: Symlink nvim executable
  file:
    src: ~/bin/nvim-{{ neovim_version }}/squashfs-root/AppRun
    dest: ~/bin/nvim
    state: link

- name: Install Plug vim package manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim
    mode: 0600

- name: Install python3 neovim lib
  pip:
    name: neovim
    executable: pip3
