- name: Install Rustup
  command: bash -c 'curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path'
  args:
    creates: ~/.cargo/bin/rustup

- name: Install Rust language server
  command: rustup component add rls rust-analysis rust-src
  args:
    creates: ~/.cargo/bin/rls

# find alternative
- name: Install fd
  command: ~/.cargo/bin/cargo install fd-find
  args:
    creates: ~/.cargo/bin/fd

# grep alternative
- name: Install ripgrep
  command: ~/.cargo/bin/cargo install ripgrep
  args:
    creates: ~/.cargo/bin/rg

# Generic watching task runner
- name: Install watchexec
  command: ~/.cargo/bin/cargo install watchexec
  args:
    creates: ~/.cargo/bin/watchexec

# tokei counts lines of code
- name: Install tokei
  command: ~/.cargo/bin/cargo install tokei --features all
  args:
    creates: ~/.cargo/bin/tokei

# markdown documentation site generator
- name: Install mdbook
  command: ~/.cargo/bin/cargo install mdbook
  args:
    creates: ~/.cargo/bin/mdbook

# Rust Analyzer language server
- name: Download rust-analyzer
  get_url:
    url: https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-04-06/rust-analyzer-linux
    dest: ~/bin/rust-analyzer
    mode: 0700
